const config = {
  project: {
    name: process.env.NEXT_PUBLIC_PROJECT_NAME || 'Senai Base',
    description: process.env.NEXT_PUBLIC_PROJECT_DESCRIPTION || 'Generated by create next app',
    url: process.env.NEXT_PUBLIC_PROJECT_URL || '#',
    currentYear: new Date().getFullYear(),
  },
  pagination: {
    pearPage: process.env.NEXT_PUBLIC_PER_PAGE || 25,
  },
  api: {
    url: process.env.NEXT_PUBLIC_API_URL || '',
  },
};

export { config };
